<?php 
$this->headTitle('Add Books');
?>
<h1><?php echo $this->escapeHtml('Add Books'); ?></h1>

<?php

	$form->setAttribute('action', $this->url('book',array('action'=>'add')));
	$form->setAttribute('method','POST');
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('title'));
	echo $this->formElement($form->get('submit'));
	echo $this->form()->closeTag();
?>


