<?php 
$this->headTitle('Edit Book');
?>
<h1><?php echo $this->escapeHtml('Edit Book'); ?></h1>

<?php
	$form=$this->form;
	$form->setAttribute('action', $this->url('book',array('action'=>'edit','id'=>$this->id)));
	$form->setAttribute('method','POST');
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->FormHidden($form->get('id'));
	echo $this->FormRow($form->get('title'));
	echo $this->FormElement($form->get('submit'));
	echo $this->form()->closeTag();
?>


